### ISSUE TITLE
Primary key is not set for indexes

### ISSUE THREAD

**Issue by thijndehaas** [meilisearch/meilisearch-php#401] opened 2022-10-18 13:48 UTC
**Description**
Every time I create the index the primary key is not set. I found this out because the index has duplicate product IDs.

**Expected behavior**
Primary key being `id`

**Current behavior**
Primary key being `null`

**Screenshots or Logs**
![afbeelding](https://user-images.githubusercontent.com/18503351/196446240-d0ce9dcc-e8f9-43d3-84c6-990cd86cc48e.png)
![afbeelding](https://user-images.githubusercontent.com/18503351/196446348-8a8e666c-17ca-4f84-a793-4d47aba624f5.png)

**Environment (please complete the following information):**
- OS: `Debian 5.10.70-1 (2021-09-30) x86_64`
- Meilisearch version: `v.0.29.1`
- meilisearch-php version: `v0.24.1` and `v0.25.0`

**Comment by brunoocasali** [comment] 2022-10-18 17:35
Hi @thijndehaas, thanks for raising the issue!

As you can check the source here:
https://github.com/meilisearch/meilisearch-php/blob/main/src/Endpoints/Indexes.php#L101-L109

the method `getPrimaryKey` does not trigger an HTTP call, but the `fetchPrimaryKey` does. Can you try this one? I believe your `$index` is storing an old reference or a not updated one to the brand new index you created.

**Comment by thijndehaas** [comment] 2022-10-19 06:38
Hi @brunoocasali, thank you this returns `id`!

However this is one of our results, they have identical values, only the updated column has changed.
![afbeelding](https://user-images.githubusercontent.com/18503351/196614722-f56d8da1-07e1-45c4-bcd8-94fee0d46957.png)

I have now cleared the entire data.ms folder and started with a clean set-up. I will check if the duplicates will come back.

**Comment by brunoocasali** [comment] 2022-10-19 17:51
@oluademola have you ever seen behavior like this? I'm inclined to treat that as a Meilisearch engine bug...

**Comment by oluademola** [comment] 2022-10-20 07:55
Hello @brunoocasali.  I believe the same. We had a user report a similar issue on the [Slack community channel](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1665160818982859), but we could not reproduce the problem 😞.

**Comment by brunoocasali** [comment] 2022-11-07 12:38
Hi @thijndehaas, I'll close this issue then. If there is something related to the PHP package I'll reopen it :)

Thanks a lot for your help ❤️

**Closed by brunoocasali** 2022-11-07 12:38 UTC
Labels: support
