### ISSUE TITLE
getAllIndexes() not returning expected array

### ISSUE THREAD

**Issue by CNSam** [meilisearch/meilisearch-php#205] opened 2021-09-10 08:39 UTC
Hi,

I'm pretty sure this is a bug, just wanted clarification.

I am using this package in Laravel without Laravel Scout and using the MeiliSearch\Client class to 'getAllIndexes()' however what is returned is an arrayu with 2 private properties, 'uid' & 'primaryKey' as opposed to the list of Indexes I was expecting.

Am I doing something wrong here?

**Comment by alallema** [comment] 2021-09-14 10:04
Hi @CNSam!
Thanks for raising this issue and sorry for the delay.
This is indeed the expected behavior, the function `getAllIndexes()` should return a list of indexes [cf: doc](https://docs.meilisearch.com/reference/api/indexes.html#list-all-indexes). An Index is composed of an `uid` and a `primaryKey`.
The `getAllIndexes()` function return an array of `Index` you need to use the getter to have access to the `uid` and the `primaryKey`.
You can acces it this way:
```php
$response = $client->getAllIndexes();
foreach ($response as $value){
    printf("%s\n", $value->fetchPrimaryKey());
    printf("%s\n", $value->getUid());
    printf("%s\n", $value->getPrimaryKey());
}
```
Maybe I missing something so don't hesitate to tell me what you expected and how I could help you.

**Comment by alallema** [comment] 2021-09-28 09:33
Closing this issue due to a lack of an answer. Feel free to re-open if needed.

**Closed by alallema** 2021-09-28 09:33 UTC
